### ISSUE TITLE
No easy way to see girls die..

### ISSUE THREAD

**Issue by KuromeSan** [SKGleba/HH-Vita#1]
*SOME* people enjoy seeing girls die you know!  
y-you should have an option to sort by anime where girls die :D   
O-or just add more channels so u can watch normal anime.. and well see girls die from there too!

**Comment by nkrapivin** [comment]
Stop hiding... I KNOW IT'S YOU! SILICAANDPINA!

**Comment by FSEC-DALMASIAN** [comment]
RIP

**Comment by FSEC-DALMASIAN** [comment]
secret blown
