### ISSUE TITLE
Suggestions for the next update (v2.5) - Post them here

### ISSUE THREAD

**Issue by SKGleba** [SKGleba/HH-Vita#3]
- "More Info" option with full description & thumbnail (done)
- Episodes count bug fix (done)
- LTRIGGER crashes if on the first entry fix (done)
- Link generator (done)
- One hand mode
- "Favorites"
- Search function

**Comment by devingDev** [comment]
- Show "HentaiHaven" in discord playing on profile

**Comment by devingDev** [comment]
> Combine both the SAFE and UNSAFE versions (i.e. vpks) of this app if possible. Perhaps prompt the user if they want to create a password (safe) or not (unsafe) when they first run the app; this should be able to be changed in the settings later if they want to switch to safe mode.
> 
> Keep and use the livearea and app theme/wallpaper of the UNSAFE version in this combined version.
> 
> Also upload this vpk to vitadb so that users can download and install future versions in the Vita Homebrew Browser app.

Probably rather easy. Add a setting to enable / disable + change pin. 
Enabling copies safe liverae to ux0/titleid/sce_sys and disabling does so with the unsafe livearea.
Then you probably have to refresh the livearea somehow to update the bg and icon
