### ISSUE TITLE
Post here movies that you want to add to the database!

### ISSUE THREAD

**Issue by SKGleba** [SKGleba/HH-Vita#4]
Example:
- title: "Gakuen De Jikan Yo Tomare"
- Episode 1: http://217.182.172.142/Gakuen%20De%20Jikan%20Yo%20Tomare%201%20Subbed.mp4 // direct http mp4 link only
- Episode 2: http://217.182.172.142/Gakuen%20De%20Jikan%20Yo%20Tomare%202%20Subbed.mp4
- etc.

Only rule: no gore stuff.

**Comment by nkrapivin** [comment]
> Only rule: no gore stuff.

Isn't this an anti-SilicaAndPina measure?

**Comment by SKGleba** [comment]
anti who?
